name: Feature Template
description: 기능 추가할 때 쓰는 템플릿
title: "[Feature]: Feature Title"
labels: ["feature"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. 타이머 화면 그리기
    validations:
      required: true
  - type: input
    id: prepare-issue
